# fly.toml app configuration file generated for lyte-bot on 2024-03-13T13:23:34-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lyte-bot'
primary_region = 'dfw'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
